slack-scala-client/slack-scala-client

src/main/scala/slack/models/SlackFile.scala
Hey Bryan,
I found that my app using your library crashes on file attachments. Investigating this, I found that format for files contains 'created' instead of 'create'. I'm not sure if it was a typo in your code or if it _used to_ work like that in Slack before, but now it is definitely `created'.
Example attachments json (in log message):
```
[INFO] [06/20/2015 15:37:58.915] [Baka-akka.actor.default-dispatcher-13] [akka://Baka/user/$a/$a] [WebSocketClient] Received Text Frame: {"type":"file_public","file":{"id":"F06KA3A7L","created":1434814676,"timestamp":1434814676,"name":"Screenshot_24.png","title":"Screenshot_24.png","mimetype":"image/png","filetype":"png","pretty_type":"PNG","user":"U04NY8SRD","editable":false,"size":50523,"mode":"hosted","is_external":false,"external_type":"","is_pub …
```
=> create -> created for SlackFile json format

src/main/scala/slack/Main.scala, src/main/scala/slack/rtm/SlackRtmClient.scala
For users of `SlackRtmClient`, the timeout of 5 seconds is hard coded. While testing, I've found occasions where 5 seconds did not suffice to establish a connection, and consequently, there were timeouts. This change exposes the timeout in the `SlackRtmClient` constructor.
=> Allow passing a timeout into SlackRtmClient

README.md
Looks like `getChannels()` is not present in the API, replaced it with
`listChannels()` insead.
=> Update README to remove getChannels()

project/Build.scala, src/main/scala/slack/models/Events.scala, src/main/scala/slack/models/package.scala, src/test/scala/TestJsonMessages.scala
Added initial support for messages with subtypes and basic tests for them. I think I followed the way you were intending to do it from the stubs you had in place.
=> Initial Message Subtype Support

src/main/scala/slack/models/Events.scala, src/main/scala/slack/models/package.scala, src/test/scala/TestJsonMessages.scala
Currently `message_changed` event, treated as `MessageWithSubtype`. But this event doesn't contain `user` element, and the parsing fails as a result.
=> Message changed event handled

project/Build.scala
Spray 1.3.3 has a commit in it honoring the HTTP proxy settings, in particular the ones you can use with the JVM: `-Dhttp.proxyHost=www.proxy.com -Dhttp.proxyPort=8088`
I need this where I have to deploy the application. I'm going to verify that it runs with a jit pack of mine and I'll comment that the dependency override worked.
=> Adding a dependency override to use spray 1.3.3 for proxy stuff

src/main/scala/slack/models/Attachment.scala
Markdown support is added to Attachments.
Ref: https://api.slack.com/docs/message-formatting
=> Markdown in Attachments

project/Build.scala, project/build.properties, src/main/scala/slack/api/SlackApiClient.scala
Added a new method `uploadFileBytes` which is identical to `uploadFile` but takes `Array[Byte]` instead of a `File`.  
This method is useful when you want to upload dynamically generated content (e.g. image) without writing it to actual OS backed file.
Along the way bumped dependencies and added explicit SBT version, optimized imports.
=> Upload bytes merge

src/main/scala/slack/models/Events.scala, src/test/scala/TestJsonMessages.scala
Adding mapping for existing payload: 'item_user' in ReactionAdded/ReactionRemoved
=> Adding 'item_user' mapping for  ReactionAdded/ReactionRemoved

src/main/scala/slack/models/Events.scala, src/main/scala/slack/models/package.scala, src/test/scala/TestJsonMessages.scala
Hey really good library however i kept getting an "Error reading event" for [dnd_updated_user](https://api.slack.com/events/dnd_updated_user) events. I noticed you had already fixed a similar issue for desktop_notification [here](https://github.com/gilbertw1/slack-scala-client/commit/69dc64dd268745db25985cc8f28bc39c2d6bbae2) so i did the same for the dnd_updated_user event. Thanks
=> Added missing dnd_updated_user event

src/main/scala/slack/models/Events.scala
Adding mapping for existing payload: "attachments" in (incoming) BotMessages
=> Adding 'attachments' mapping for BotMessages

src/main/scala/slack/api/BlockingSlackApiClient.scala, src/main/scala/slack/api/SlackApiClient.scala
Just added `thread_ts` to `chat.postMessage`.
Currently available at https://jitpack.io/#yewton/slack-scala-client_2.12/jitpack-SNAPSHOT
=> Thread support api client

src/main/scala/slack/models/Events.scala, src/main/scala/slack/models/package.scala
Hey, I am using this client in combination with the Events API.
However, in order to do so, the modeled events in `Events.scala` have to be wrapped by event type structure of slack (see https://api.slack.com/events-api#event_type_structure).
Furthermore, an server challenge is sent to the url that one provides when subscribing for slack events (see https://api.slack.com/events/url_verification). Therefore, this event has to be modeled.
This PR enables using the defined events of this repo with slack Events API.
I am already using this for few events.
Kind regards
=> Enable to use slack Events API

src/main/scala/slack/api/BlockingSlackApiClient.scala, src/main/scala/slack/api/SlackApiClient.scala, src/main/scala/slack/rtm/SlackRtmClient.scala
Now SlackApiClient/BlockingSlackApiClient/SlackRtmClient accept an optional slackApiBaseUri. If it is not provided then `SlackApiClient.defaultSlackApiBaseUri` is used which is `https://slack.com/api/`
`SlackApiClient` and `BlockingSlackApiClient` now can be easily tested with [wiremock](http://wiremock.org/) since they are just simple HTTP calls.
`SlackRtmClient` needs a websocket server mocking Slack RTM api. It is still missing but one step closer.
=> make slack url configurable - address Issue #67

src/main/scala/slack/api/BlockingSlackApiClient.scala, src/main/scala/slack/api/SlackApiClient.scala
Not sure if tests can be added here since the existing methods don't have them
=> Add support for https://api.slack.com/methods/users.lookupByEmail

src/main/scala/slack/api/SlackApiClient.scala
The Slack API `chat.postMessage` requires the content type to be `Content-type: application/json; charset=utf-8`.  This should be the default when setting the content type using the Scala DSL `withEntity(ContentTypes.`application/json`, entity)`.  The [Akka HTTP docs](https://doc.akka.io/docs/akka-http/current/common/http-model.html#http-headers) also note that Content Type should not be included as an explicit header. 
This PR fixes this scenario by removing the Java DSL explicit Content Type header and replacing it with the Scala DSL method of adding it to the entity instead.
fixes #108
=> Fix Content-Type to use correct charset

build.sbt, project/plugins.sbt
Enabling Scapegoat static analysis tool as something you can optionally run with `scapegoat` in `sbt`
=> Enabling scapegoat

src/test/scala/slack/Credentials.scala, src/test/scala/slack/SlackApiClientTest.scala, src/test/scala/slack/SlackRtmClientTest.scala
Due to / Thanks to the way secrets are handled by Travis CI for *open-source* project like this, we cannot run the integration tests towards real Slack for pull requests. As that would cause the credentials to leak.
So we skip the tests when API credentials are unavailable.
And we continue to run these two tests if they are available - that is:
- either it's a master run in Travis CI
- or someone specifies the credentials manually in their local `src/test/resources/application.conf`
This is kind of lame with this one huge case/match. I haven't found a cleaner way in Scalatest. https://stackoverflow.com/q/32460295/118587 suggests it's doable, but:
- I didn't try the Tags
- the `cancel` or `assume` is not what we need here, as it causes a failure, not skipping of a test
=> Skipping tests if credentials don't exist

src/main/scala/slack/api/SlackApiClient.scala, src/test/scala/slack/SlackApiClientTest.scala
Fixes #113 by removing the question-mark encoding workaround.
Now the tests pass with Scala 2.13 too.
So basically it's a revert of the old workaround added in #60
=> Removing question-mark encoding workaround.

src/main/scala/slack/api/SlackApiClient.scala, src/main/scala/slack/rtm/SlackRtmClient.scala, src/main/scala/slack/rtm/WebSocketClientActor.scala
Minor refactor fixes based on Scapegoat reports.
One I actually believe is not a refactoring, but a real fix:
```
case SendPing =>
```
I suspect this didn't work before.
=> Fixing warnings

RELEASING.md, src/main/scala/slack/api/BlockingSlackApiClient.scala, src/main/scala/slack/api/SlackApiClient.scala, src/main/scala/slack/rtm/WebSocketClientActor.scala, src/test/resources/application.conf.template, src/test/resources/travis.application.conf
Added optional support for using proxy.
Default is not to use proxy, most changes are in private functions while public functions get defaults and keep current logic of no proxy and code changes are needed.
Instead of just using implicit system in each api function - I added an implicit system to clients generation to get the needed config in there.
=> Add proxy support

src/main/resources/reference.conf, src/main/scala/slack/api/SlackApiClient.scala
The default timeout of 10 seconds for `toStrict` in API requests is not long enough for big organizations which have a very large state. In particular, initializing a `SlackRtmClient` is prone to fail on a `java.util.concurrent.TimeoutException`. This patch tries to make the timeout configurable.
=> Make toStrict timeout configurable

src/main/scala/slack/models/Events.scala, src/test/scala/slack/TestJsonMessages.scala
Adding support for attachments in plain Messages. Until now they have only been mapped in `BotMessages`
=> Adding support for attachments in plain Messages

src/main/scala/slack/rtm/SlackRtmClient.scala
Expose unfurl option parameters added in https://github.com/slack-scala-client/slack-scala-client/pull/162
=> Expose unfurl parameters in SlackRtmClient

src/main/scala/slack/api/SlackApiClient.scala
Tested by creating a test app using the listChannels route. No longer receives `invalid_auth` error. 
Uses same implementation as `makeJsonApiRequest`
=> fix issue with token

project/Build.scala
For no specific reason other than staying up to date.
https://doc.akka.io/docs/akka-http/current/compatibility-guidelines.html says:
> Akka HTTP 10.2.x is (binary) compatible with Akka >= 2.5.32 and Akka >= 2.6.8 and future Akka 2.x versions that are released during the lifetime of Akka HTTP 10.2.x.
=> Upgrading to akka-http 10.2

CHANGELOG.md, project/Build.scala
Fixes #201.
Other than the obvious "let's keep up with the progress" reasons. The trigger was that the latest akka-http doesn't support Scala 2.11
=> Dropping support for Scala 2.11

src/main/scala/slack/api/SlackApiClient.scala
At some point, im.open stopped working, returning an error about the method being deprecated.
Luckily, the new conversation.open/close arguments are very similar.
This PR adds a minor change fixing these two methods (only).
I believe other methods should be migrated as well at some point (history, list, mark), but I have no capacity to implement and test them.
However, .open and .close are tested and work well (refs https://github.com/Firfi/slack-baka/commit/1821d16b8c0f1fe9d276980f271f7b8a2ea56a7a which uses my fork now)
=> Update deprecated im.open and im.close API endpoints

src/main/scala/slack/api/SlackApiClient.scala, src/main/scala/slack/rtm/WebSocketClientActor.scala
In Akka 2.6 (#220) `ActorMaterializer` is deprecated. The warnings given are:
```
method apply in object ActorMaterializer is deprecated (since 2.6.0): Use the system wide materializer or Materializer.apply(actorContext) with stream attributes or configuration settings to change defaults
[error]     implicit val materializer: ActorMaterializer = ActorMaterializer(
```
TBH, I don't want it is, but following https://stackoverflow.com/a/58768480/118587 I assume it's fine to remove it. Since we already have `ActorSystem` implicit available in these scopes.
=> Removing mentions of ActorMaterializer

models/src/main/scala/slack/models/Channel.scala, src/test/scala/slack/TestJsonMessages.scala
My slackbot has conv with only 2 IM channels, which resulted `listConversations()`  with the following error:
`JsResultException(errors:List(((0)/name,List(JsonValidationError(List(error.path.missing),List()))), ((1)/name,List(JsonValidationError(List(error.path.missing),List())))))`
the channels are practically nameless so in order to fix the json validation error, I just fixed by not expecting a name.
=> channel's name to be optional

README.md, project/Build.scala, src/main/resources/reference.conf, src/main/scala/slack/Main.scala, src/main/scala/slack/api/BlockingSlackApiClient.scala, src/main/scala/slack/api/RetryAfter.scala, src/main/scala/slack/api/SlackApiClient.scala, src/main/scala/slack/rtm/SimpleEventHandlers.scala, src/main/scala/slack/rtm/SlackRtmClient.scala, src/main/scala/slack/rtm/WebSocketClientActor.scala, src/test/scala/slack/Credentials.scala
**What**:
- Closes #273.
- Migrates to Pekko instead of Akka
**Why**
Because of the Akka license change after 2.6.
=> Migrating to Pekko

.github/workflows/scala.yml
**What**:
Defining two CI jobs to be run by Github Actions:
- one with current setup (Java 8, Scala 2.12)
- the new one with Java 11 and Scala versions
**Why**:
Because I think we have violated the Java 8 compatibility by accident by using Play 2.10. It seems to be practically:
- supporting Java 8 for Scala 2.12 builds
- requiring Java 11 for Scala 2.13+ builds
=> Two CI jobs
