slack-scala-client/slack-scala-client

src/main/scala/slack/models/Events.scala, src/main/scala/slack/models/SlackFile.scala, src/main/scala/slack/models/package.scala
Improving behavior for messages with subtypes, as well as adding reactions.
=> Adding new events and fixing some. 

src/main/scala/slack/rtm/SlackRtmClient.scala
Passing the timeout setting through another instance of BlockingSlackApiClient.
=> Fixing timeout handling.

.travis.yml, README.md, project/Build.scala, src/main/scala/slack/api/BlockingSlackApiClient.scala, src/main/scala/slack/api/SlackApiClient.scala, src/main/scala/slack/models/Attachment.scala, src/main/scala/slack/models/Channel.scala, src/main/scala/slack/models/Events.scala, src/main/scala/slack/models/SlackFile.scala, src/main/scala/slack/models/SlackFileId.scala, src/main/scala/slack/models/Team.scala, src/main/scala/slack/models/UpdateResponse.scala, src/main/scala/slack/models/User.scala, src/main/scala/slack/models/package.scala, src/main/scala/slack/rtm/SlackRtmClient.scala, src/test/scala/SlackApiClientTest.scala, src/test/scala/SlackRtmClientTest.scala, src/test/scala/TestJsonMessages.scala
@gilbertw1 please review, thanks
=> added optional params to identify private channel from multi people chat

project/Build.scala
The only thing needed is to bump the version numbers to 2.5.3
No code changes needed, everything works great. Hooray for easy fixes!
I also bumped the version number to 1.5, because I needed it in my app.
=> Play update

src/main/scala/slack/api/SlackApiClient.scala, src/main/scala/slack/models/App.scala, src/main/scala/slack/models/Events.scala, src/main/scala/slack/models/SlackComment.scala, src/main/scala/slack/models/SlackFile.scala, src/main/scala/slack/models/User.scala, src/main/scala/slack/models/package.scala
* Added `replace_original` and `delete_original ` params to actions
* Added type `App` to handle `apps_changed ` and `apps_uninstalled ` events
* Added `tz_offset ` to `User`
* Updated `file_share` message subtype to handle `SlackFile`
* Fixed typo in comment `timestamp`
=> Model and API changes

src/main/scala/slack/models/Events.scala, src/main/scala/slack/models/ReactionItem.scala, src/main/scala/slack/models/package.scala, src/test/scala/SlackRtmClientTest.scala, src/test/scala/TestJsonMessages.scala
handled reactions and `mpim_joined` event
=> Support for Reaction item and MPIM event

.gitignore, src/test/resources/application.conf.template, src/test/scala/SlackApiClientTest.scala, src/test/scala/SlackRtmClientTest.scala
=> fix tests so that they don't have API & channel keys embedded in them.

src/main/scala/slack/models/Events.scala, src/main/scala/slack/models/package.scala, src/main/scala/slack/rtm/SlackRtmClient.scala
follow the example in #44 and add desktop_notification slack event.
@gilbertw1 , i included @sammyrulez's #44 changes in this PR.  so, you can just merge this one instead of merging both.  It can save you some conflict resolving effort.
=> suppress desktop_notification error

.gitignore, project/Build.scala, src/main/scala/slack/models/Events.scala, src/main/scala/slack/rtm/SlackRtmClient.scala
For now just adding support on RTM.
@gilbertw1 please review
=> Send and receive messages with threads

src/main/scala/slack/api/SlackApiClient.scala
@gilbertw1 Support for MPIM commands
Methods included
- mpim.open
- mpim.close
- mpim.list
- mpim.mark
- mpim.history
=> Added MPIM commands

src/main/scala/slack/api/BlockingSlackApiClient.scala, src/main/scala/slack/api/SlackApiClient.scala
[channels.replies method | Slack](https://api.slack.com/methods/channels.replies)
=> Support channels.replies

src/main/scala/slack/models/Events.scala
Handling Bots editing their messages.
That is to prevent error messages like this:
```
play.api.libs.json.JsResultException: JsResultException(errors:List((/previous_message/user,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/message/user,List(JsonValidationError(List(error.path.missing),WrappedArray())))))
```
=> Handling Bots editing their messages.

src/main/scala/slack/models/Attachment.scala
Please see slack attachment doc: https://api.slack.com/docs/message-attachments
=> Added footer and ts fileds for Attachment model

project/Build.scala
=> Upgrade play-json. Fixes #89

project/Build.scala
Upgrading Akka libraries. Fixes #87
=> Upgrading Akka libraries. Fixes #87

src/main/scala/slack/api/BlockingSlackApiClient.scala, src/main/scala/slack/api/SlackApiClient.scala
Adding broadcast option
[Slack Docs](https://api.slack.com/methods/chat.postMessage)
=> Add replyBroadcast option to post message

src/main/scala/slack/rtm/SlackRtmClient.scala
=> Restart connection actors on failures.

src/main/scala/slack/rtm/RtmState.scala, src/main/scala/slack/rtm/SlackRtmClient.scala, src/main/scala/slack/rtm/WebSocketClientActor.scala
Fixes #105 by adding explicit :Unit return type
=> Fixes #105 by adding explicit :Unit return type

src/main/scala/slack/models/package.scala, src/main/scala/slack/rtm/SlackRtmClient.scala
=> Scapegoat Refactor - removing Option.get calls

src/main/scala/slack/SlackUtil.scala, src/main/scala/slack/api/SlackApiClient.scala, src/main/scala/slack/rtm/SlackRtmClient.scala, src/main/scala/slack/rtm/WebSocketClientActor.scala, src/test/scala/slack/SlackUtilTest.scala
Fixing some warnings mostly reported by Scapegoat (#130)
=> Fixing warnings

src/main/scala/slack/models/Events.scala, src/main/scala/slack/models/Team.scala, src/main/scala/slack/models/package.scala, src/test/scala/slack/TestJsonMessages.scala
Adding mapping for events I observe as errors in my logs. I don't need them necessarily:
- `app_actions_updated`
- `subteam_created`
- `subteam_updated`
=> Adding missing models

src/main/scala/slack/rtm/SlackRtmClient.scala
Fixing regression about ping, which after recent changes (in #118) were no longer sent
=> Fixing ping

src/main/scala/slack/rtm/SlackRtmClient.scala, src/main/scala/slack/rtm/WebSocketClientActor.scala
Opening up for extending the `SlackRtmClient` - I mostly need it for the Slack Dumper.
=> Opening up for subclassing

src/main/scala/slack/models/Events.scala, src/main/scala/slack/models/package.scala, src/test/scala/slack/TestJsonMessages.scala
=> Fixing replies to bot messages

src/main/scala/slack/rtm/SlackRtmClient.scala
As specificed in https://api.slack.com/methods/chat.postMessage
=> Add support for unfurl_links & unfurl_media

project/Build.scala
Reverts slack-scala-client/slack-scala-client#226 as I've accidentally merged that. It's not ready yet.
=> Revert "Update akka-actor, akka-stream to 2.6.19"

build.sbt, project/Build.scala, src/main/scala/slack/api/SlackApiClient.scala, src/main/scala/slack/rtm/SlackRtmClient.scala, src/test/scala/slack/SlackRtmClientTest.scala
=> Akka 2.6.19, fixes #220

models/src/main/scala/slack/models/Events.scala, models/src/main/scala/slack/models/package.scala, src/test/resources/json-messages/message-channel_topic.json
JSON gathered by https://github.com/slack-scala-client/slack-dumper
=> Adding support for `channel_topic` subtype of message

README.md
The previous link was broken :D
=> Correct Events.scala location on README

models/src/main/scala/slack/models/Events.scala, models/src/main/scala/slack/models/package.scala, src/test/resources/json-messages/user_change.json, src/test/resources/json-messages/user_huddle_changed.json, src/test/resources/json-messages/user_profile_changed.json
=> Adding support for UserHuddleChanged and UserProfileChanged

models/src/main/scala/slack/models/User.scala, src/test/resources/json-messages/user_profile_changed.json
Related to #254
It turns out the profile JSON received from Slack doesn't contain some fields. Marking them as optional. This is to avoid errors like this one:
```
play.api.libs.json.JsResultException: JsResultException(errors:List((/user/profile/image_192,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/user/profile/image_48,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/user/profile/image_72,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/user/profile/image_32,List(JsonValidationError(List(error.path.missing),WrappedArray()))), (/user/profile/image_24,List(JsonValidationError(List(error.path.missing),WrappedArray())))))
```
=> Refreshing UserProfile case class

models/src/main/scala/slack/models/Events.scala, src/test/resources/json-messages/message-message_changed.json
Adding support for attachments in message_changed.
In my case it was about Atlassian Jira Cloud which comes with some fancy section every time you post a link to a Jira issue.
=> Adding support for attachments in message_changed

build.sbt, project/Build.scala, src/main/scala/slack/api/SlackApiClient.scala, src/main/scala/slack/rtm/WebSocketClientActor.scala, src/test/scala/slack/JsonMessagesDeserializationTest.scala, src/test/scala/slack/TestJsonMessages.scala
**What**:
Adding support for Scala 3.
(thus closing #232 and replacing #268)
**Why**:
Just to stay up-to-date.
=> Scala3 support (attempt 2)
